project:
  type: website
  output-dir: docs

website:
  title: "Rick Brown"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: About
      - href: teaching.qmd
        text: Teaching
      - text: Course Pages
        menu:
          - href: math3190s26.qmd
            text: MATH 3190 Spring 2026
      - text: Course Notes PDFs
        menu: 
          - href: Course Notes/Math 1040 Notes - All Chapters.pdf
            text: MATH 1040
          - href: Course Notes/Math 3150 Notes - All Chapters.pdf
            text: MATH 3150
          - href: math3190/Notes/All Notes/Math 3190 Notes - All.pdf
            text: MATH 3190
          - href: Course Notes/Math 3700 Notes - All Chapters.pdf
            text: MATH 3700
          - href: Course Notes/R-Guide.pdf
            text: R Guide
      - href: workshops.qmd
        text: Conference Workshops
      - text: Fun with R Shiny
        menu:
          - href: Shiny Apps/R Shiny App - kmeans.qmd
            text: K-Means
          - href: Shiny Apps/R Shiny App - correlation.qmd
            text: Correlation Game
      - text: Miscellaneous
        menu: 
          - href: LaTeX Accessible Guide.pdf
            text: LaTeX Accessibility Guide

format:
  html:
    theme: cosmo dark
    css: styles.css
    toc: true



